### ISSUE TITLE
Attribute information improvements

### ISSUE THREAD

**Issue by Misjohns** [instructlab/ui#153]
**Existing implementation**
The existing form places the URL after the name requiring user to manually enter all fields

**UX recommendations**

- Place URL as the first field
- If the URL can be validated it can be used to populate the remaining fields.

![image](https://github.com/user-attachments/assets/93fd6438-7c4c-4a81-9dac-989cd61429c3)

**Comment by ediazgallego** [comment]
Hi @Misjohns and @vishnoianil I would like to work on this issue as my first contribution to the UI side of instructlab

**Comment by vishnoianil** [comment]
@ediazgallego awesome, please feel free to assign the issue to your self. If you need any help with the dev environment setup, please feel free to ping us on the UI slack channel in instructlab workspace. More details about the weekly community meeting and slack channel here - https://github.com/instructlab/ui?tab=readme-ov-file#community-meeting

**Comment by ediazgallego** [comment]
@vishnoianil thanks, I probably do not have enough permissions yet to assign the issue to myself, anything I should request or do to get that enabled?

**Comment by vishnoianil** [comment]
> @vishnoianil thanks, I probably do not have enough permissions yet to assign the issue to myself, anything I should request or do to get that enabled?

@ediazgallego This should be fixed now.

**Comment by vishnoianil** [comment]
> Hi @Misjohns I'm currently looking into this issue, I've made the change so the URL field is the first in the section but I'm not 100% sure how to test the second bullet point you mention `If the URL can be validated it can be used to populate the remaining fields.` , can you explain a little bit more the expectations? Is there some kind of logic that will use the URL value to gather information for the subsequent fields and fill them automatically?

@ediazgallego Knowledge submission can be sourced from various targets. A simple example would be wikipedia. If user adds the URL to a wikipedia page, we should automatically populate other fields (title, revision, license, author) from wikipedia page.

At this point we can target wikipedia, because upstream taxonomy repo only accepting knowledge contribution based on the wikipedia. In future we will add support for more sources for knowledge contribution, and the extraction process for attribution information can be very specific to each target as well.

You can follow this scripts `https://github.com/mairin/instructlab-knowledge-utils?tab=readme-ov-file#1-%EF%B8%8F-wikipedia-attribution-genpy ` to determine how we can populate this information from wikipedia. Big thanks to @mairin for writing these utilities.
