### ISSUE TITLE
Improve "Access Denied" page

### ISSUE THREAD

**Issue by toraponibm** [instructlab/ui#267]
When the user logs in with their github account, after confirming the app access they are redirected back to the error page if they're not part of the org member.

The current page just contains the link back to the app top page as well as the github org https://github.com/instructlab . Since this is the likely flow which any first-time user goes into, we should provide some more information.
- Put a concise instruction on how to request access. 
- Review the design and ideally show the view in a consistent look as other pages.

<img width="1722" alt="Screenshot 2024-10-14 at 9 33 50 AM" src="https://github.com/user-attachments/assets/39a0b1ed-ca5b-4b96-bbcd-d25e3f02ac3d">

**Comment by vinhyan** [comment]
Hi @vishnoianil & @toraponibm! I'd like to give this a try please if possible. 

Thank you!

**Comment by vishnoianil** [comment]
> Hi @vishnoianil & @toraponibm! I'd like to give this a try please if possible.
> 
> Thank you!

@vinhyan awesome. thanks for picking this up. We has some brainstorming around this in last community UI meeting.

Currently for user to access the UI, they need to join the "instructlab-public" organization. User can join this organization by invitation from the admins. Admins sends the invitation using an inviter app. This inviter app requires user's github email address and a password, and admin's are the one has access to the password.

In last community meeting it was decided that we would like to remove the requirement for the password or we share the password on this 404 page itself. 

Once user authenticate and see 404 due to not part of the instructlab-public org, they should be displayed 404 page, with the details like "You need to be part of the InstructLab public org to be part of this organization. This page will redirect to the self invitation page. Please user the password "xxxxx" and the email address associated with your github account to send the invitation. Once you receive the invitation, and accept the invitation, it should allow you to access the ui.instructlab.ai." 

Bit of a strech goal is, if we can show the password initially invisible (******) and provide a button that toggle to visible, that would be helpful to prevent spams from bots.

cc: @nerdalert what do you think?

**Comment by vinhyan** [comment]
Hi @vishnoianil, thank you for the detailed explanation!

It seems we're still deciding between removing the password entirely or sharing it on the 404 page. Please let me know once a decision has been made, and I'll implement it accordingly.

For the UI on the 404 page, I'm considering using the same design as the `githublogin.tsx` page to keep everything cohesive. Let me know if that works, or any ideas/suggestions would be helpful:

![githublogin](https://github.com/user-attachments/assets/d2237a4c-9202-4edc-907f-3f672b3c53c5)

**Comment by vishnoianil** [comment]
hey @vinhyan, @nerdalert and myself had a discussion around how we can make this invitation process more seamless. Based on PR #278 from @nerdalert, i cooked up the following PR #282 . This PR actually removes the need of error 404 page itself. 

Please review #282 and provide your thoughts.

**Comment by vinhyan** [comment]
Hi @vishnoianil! Thanks for the update - this flow is definitely more seamless compared to redirecting the user to the 404 page :)

**Comment by vishnoianil** [comment]
Issue fixed through #282
