### ISSUE TITLE
Local Taxonomy features to the current experimental feature

### ISSUE THREAD

**Issue by nerdalert** [instructlab/ui#335]
- Provide the user the ability to select an existing taxonomy from a base directory. I don't know that we need to check if the directory is a taxonomy for now, just the raw path. Ideally a popup starting at the base directory.
- We support initializing a new clone from an upstream repo. Up to the user would need to ensure its a fork etc.
- Add knowledge file support. We need to replicate how the SaaS handles knowledge files for now. There needs to be a new repo initialized for knowledge docs and still create an attribution.txt file until this changes upstream to a more streamlined doc ingestion into a vectordb.

**Comment by vishnoianil** [comment]
This issue is being addressed through #412 . For the native mode (local git contribution) we ask user to provide the location of their taxonomy. UI pushes all the contribution to thier repository. For knowledge documents submission, UI clones taxonomy-knolwedge-docs parallel to the taxonomy repo and commit the docs to it. Main knowledge contribution yaml points to the directory where taxonomy-knowledge-docs repo is cloned and the respective commit sha. @nerdalert please feel free to re-open the issue if you see any specific ask is not addressed yet.
