### ISSUE TITLE
Issue Running InstructLab UI - Need Help with .env Variables

### ISSUE THREAD

**Issue by Branchenprimus** [instructlab/ui#37]
Hi team,

Thank you for developing the InstructLab UI! I'm excited to start using it, but I'm currently having trouble getting it up and running. The main issue seems to be understanding and setting the `.env` variables.

Here's what I have in my `.env` file:

```
IL_UI_ADMIN_USERNAME=admin
IL_UI_ADMIN_PASSWORD=password
OAUTH_GITHUB_ID=<OAUTH_APP_ID>
OAUTH_GITHUB_SECRET=<OAUTH_APP_SECRET>
NEXTAUTH_SECRET=your_super_secret_random_string
NEXTAUTH_URL=http://localhost:3000
IL_GRANITE_API=<GRANITE_HOST>
IL_GRANITE_MODEL_NAME=<GRANITE_MODEL_NAME>
IL_MERLINITE_API=<MERLINITE_HOST>
IL_MERLINITE_MODEL_NAME=<MERLINITE_MODEL_NAME>
GITHUB_TOKEN=<TOKEN FOR OAUTH INSTRUCTLAB MEMBER LOOKUP>
TAXONOMY_DOCUMENTS_REPO=github.com/<USER_ID>/<REPO_NAME>
NEXT_PUBLIC_TAXONOMY_REPO_OWNER=<GITHUB_ACCOUNT>
NEXT_PUBLIC_TAXONOMY_REPO=<REPO_NAME>
```

* **Could you please provide a brief explanation of what each variable does?** Some of them seem self-explanatory (like OAUTH_GITHUB_ID/OAUTH_GITHUB_SECRET), but others are less clear.
* **Where can I obtain the values for each variable?**  For example, I'm not sure where to get the IL_GRANITE_API key or how to generate the `NEXTAUTH_SECRET`.

Any guidance would be greatly appreciated!

Thanks,
Jan

**Comment by nerdalert** [comment]
Hi @Branchenprimus!

- `NEXTAUTH_SECRET` is in the NextAuth docs but I don't really see the need for it atm. It could be removed if you want to open a PR or I can otherwise.
- `OAUTH_GITHUB_ID/OAUTH_GITHUB_SECRET` are kicked back when you create an OAuth. You could setup your own for example. Here is a screen cap of one that would work if you were running on your local machine. The key item is the callback URL needs to match your URL of the service. So `http://localhost:3000/api/auth/callback/github` would work for starting the service with `npm run dev` and going to `http://localhost:3000`.
<img width="845" alt="oauth-example" src="https://github.com/instructlab/ui/assets/1711674/f6884176-f188-4e0b-9d12-3da7a8639bd9">
- For `IL_GRANITE_API` and `IL_MERLINITE_MODEL_NAME` those are locked down in a security group since they are running non-quantized version of the models on A100s so they are not exposed to the Internets at the moment. What you can do in the meantime is create your own custom endpoint that could be instructlab running on your machine or anywhere and hit a quantized version.
<img width="1190" alt="image" src="https://github.com/instructlab/ui/assets/1711674/30ceec06-bd0c-4dce-ada5-733d1faba8ab">
- If you want to hit me up on [Slack](https://github.com/instructlab/community/blob/main/InstructLab_SLACK_GUIDE.md) and you're looking to dev don't hesitate and we can figure out access to the non-quant. Also the community UI meeting is tomorrow at 1pm EST if you feel like popping in! Link to [calendar](https://calendar.google.com/calendar/u/0/embed?src=c_23c2f092cd6d147c45a9d2b79f815232d6c3e550b56c3b49da24c4b5d2090e8f@group.calendar.google.com)

Cheers!

**Comment by aevo98765** [comment]
Hey @Branchenprimus, did you and @nerdalert resolve this one or can we help with anything?

**Comment by vishnoianil** [comment]
This issue is open for a while without any activity. @Branchenprimus I am closing this issue, but if you still not able to setup your local environment, please reopen the issue or hit us at the UI slack channel [here](https://github.com/instructlab/ui?tab=readme-ov-file#slack-channel) and contributors will be happy to jump on fix your dev environment issues. Thanks!
