### ISSUE TITLE
github authentication on ui.instruct.lab should not request WRITE access to all my repos

### ISSUE THREAD

**Issue by fche** [instructlab/ui#405]
That seems excessive.

**Comment by vishnoianil** [comment]
@fche Currently UI stack ask for token with "public_repo" scope, that gives access to user's public repositories. UI can't see the private repository. Although this can be improved further by using the fine-grained access tokens. Currently we use OAuth app that doesn't allow us to request repository level access token, but switching to Github Auth App can allow us to request even more fine trace access token. If you have the bandwidth and like to contribute the PR, I would love to review the PR.

**Comment by fche** [comment]
Can you explain why public_repo is needed at all, which includes "read/write access to code, commit statuses, repository projects, collaborators, and deployment statuses"?  As opposed to say "read:user" ?

**Comment by vishnoianil** [comment]
> Can you explain why public_repo is needed at all, which includes "read/write access to code, commit statuses, repository projects, collaborators, and deployment statuses"? As opposed to say "read:user" or even "(no scope)" ?

@fche InstructLab Knowledge contribution requires the source of the knowledge to be referenced in the contribution. It requires user to upload the related document to the github and use the commit SHA to be added in the qna.yaml file. You can see more details about knowledge contribution here -> https://docs.instructlab.ai/taxonomy/knowledge/contribution_details/

In UI project we don't want to store user documents in InstructLab owned github repository (due to multiple issues around ownership etc), that's why UI clones an archived github repo (https://github.com/instructlab-public/taxonomy-knowledge-docs) to the **user account** and upload the document to to it, so that the document stays in user's own github repository. And this process requires write permission to clone and commit the document. Hope it helps answer your question. Let me know if you have any follow-up question.
